### ISSUE TITLE
Main.py missing

### ISSUE THREAD

**Issue by TipluLeon** [Unbrick/Jodel-Keyhack-v3#10]
Hi.

Im trying to set this up but backend/main.py is missing

Regards
Leon

**Comment by TipluLeon** [comment]
Taking a main.py from previous commits leads to the problem that magic isnt installed.
Im using mac os und tried with `brew install libmagic` but it didnt work. The magic bib isnt listed in requirements.txt

**Comment by Unbrick** [comment]
I tried to push the server to production, in order to do this I needed to create a module, so I just renamed the main.py to __init__.py, using this one it should work

**Comment by TipluLeon** [comment]
ah ok. but the problem with the magic still exists
```
File "backend/__init__.py", line 6, in <module>
    import magic
ModuleNotFoundError: No module named 'magic'
```

**Comment by TipluLeon** [comment]
Figured it out by installing these packages:
`pip3 install python-libmagic python-magic-bin`

but now i get the following error:
```
$ python3 backend/__init__.py
Traceback (most recent call last):
  File ".\__init__.py", line 7, in <module>
    import backend.decrypt as decrypt
ModuleNotFoundError: No module named 'backend' 
```

**Comment by TipluLeon** [comment]
I just moved
```
import backend.decrypt as decrypt
import backend.r2instance as R2Instance
```
to
```
import decrypt as decrypt
import r2instance as R2Instance
```

**Comment by Unbrick** [comment]
Great to hear it worked finally! Could you just fork it and create a pull request with your working version?

**Comment by TipluLeon** [comment]
Thx. Havent had time for it! :)
